
spring:
  profiles:
    active: local

---
spring:
  profiles: local
  jpa:
    show-sql: true



#---
#spring:
#  profiles: set1
#server:
#  port: 8081
#---
#spring:
#  profiles: set2
#server:
#  port: 8082
